name = "xerelle"
main = "src/index.js"
compatibility_date = "2026-07-28"

[[d1_databases]]
binding = "DB"
database_name = "xerelle-db"
database_id = "7ac14e50-89a7-423e-996d-b7de4dc5faaf"


[[r2_buckets]]
binding = "MEDIA"
bucket_name = "xerelle-media"

[[kv_namespaces]]
binding = "SESSIONS"
id = "ccf869e22f33449dba34066b76765f8e"


[assets]
directory = "./public"
binding = "ASSETS"
